# Generated by Django 4.1.5 on 2023-01-23 16:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coreApp', '0002_balance_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Balance',
            new_name='BankAccount',
        ),
        migrations.RenameField(
            model_name='bankaccount',
            old_name='amount',
            new_name='balance',
        ),
    ]
