# Generated by Django 4.1.5 on 2023-01-24 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0003_rename_balance_bankaccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='lastDailyReward',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 23, 16, 56, 5, 14080, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
